apiVersion: v1
kind: Service
metadata:
  name: aevservices
  labels:
    app: aevservices
    zone: qa
    version: v1.0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: aevservices
    zone: qa
    version: v1.0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aevservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aevservices
        zone: qa
        version: v1.0
    spec:
      containers:
      - name: aevservices
        image: colsagenciavirtualpruebas.azurecr.io/agenciadeempleovirtualback:1.1
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
            - name: TableStorage
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: TableStorage
            - name: SendMailApiKey
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: SendMailApiKey
            - name: OpenTokApiKey
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: OpenTokApiKey
            - name: LdapServiceApiKey
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: LdapServiceApiKey
            - name: BlobContainer
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: BlobContainer
            - name: BlobContainerSubsidy
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: BlobContainerSubsidy
            - name: EmailAddressFrom
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: EmailAddressFrom
            - name: EmailHost
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: EmailHost
            - name: EmailHostPort
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: EmailHostPort
            - name: LdapFlag
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: LdapFlag
            - name: LdapServices
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: LdapServices
            - name: OpenTokServiceIG
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: OpenTokServiceIG
            - name: PdfConvertService
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: PdfConvertService
            - name: StorageAccountName
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: StorageAccountName
            - name: ClientIdLdap
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: ClientIdLdap
            - name: ClienteSecretoLdap
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: ClienteSecretoLdap
            - name: UrlAccessToken
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: UrlAccessToken
            - name: ClientIdLdapPass
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: ClientIdLdapPass
            - name: ClienteSecretoLdapPass
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: ClienteSecretoLdapPass
            - name: UrlApigeeFosfec
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: UrlApigeeFosfec
            - name: URLFront
              valueFrom:
                secretKeyRef:
                  name: aev-appsecrets
                  key: URLFront      
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: pull-secret-colsubsidio