//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeEmpleoVirutal.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenciaDeEmpleoVirutal.Entities.Resources.EntityMessages", typeof(EntityMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo dirección es obligatorio.
        /// </summary>
        public static string Address_Required {
            get {
                return ResourceManager.GetString("Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El telefono no es valido.
        /// </summary>
        public static string CellPhon_Number {
            get {
                return ResourceManager.GetString("CellPhon_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar por lo menos un telefono de contacto.
        /// </summary>
        public static string Cellphones_Required {
            get {
                return ResourceManager.GetString("Cellphones_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo ciudad es obligatorio.
        /// </summary>
        public static string City_Required {
            get {
                return ResourceManager.GetString("City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo nombre de contacto es obligatorio.
        /// </summary>
        public static string ContactName_Required {
            get {
                return ResourceManager.GetString("ContactName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del dispositivo es requirido para realizar el registro.
        /// </summary>
        public static string Device_Required {
            get {
                return ResourceManager.GetString("Device_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no es valido.
        /// </summary>
        public static string EmailAddress_FormatEmail {
            get {
                return ResourceManager.GetString("EmailAddress_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electronico es requerido.
        /// </summary>
        public static string EmailAddress_Required {
            get {
                return ResourceManager.GetString("EmailAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo genero es obligatorio.
        /// </summary>
        public static string Genre_Required {
            get {
                return ResourceManager.GetString("Genre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Id es obligatorio.
        /// </summary>
        public static string Id_Required {
            get {
                return ResourceManager.GetString("Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id del dispocitivo es obligatorio.
        /// </summary>
        public static string IdDevice_Required {
            get {
                return ResourceManager.GetString("IdDevice_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido es obligatorio.
        /// </summary>
        public static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la contraseña debe tener minimo 8 caracteres.
        /// </summary>
        public static string Password_LengthPassword {
            get {
                return ResourceManager.GetString("Password_LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo contraseña es obligatorio.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo del funcionario es obligatorio.
        /// </summary>
        public static string Position_Required {
            get {
                return ResourceManager.GetString("Position_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol del empleado es requerido.
        /// </summary>
        public static string Role_Required {
            get {
                return ResourceManager.GetString("Role_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo razón social de la emresa es obligatorio.
        /// </summary>
        public static string SocialReason_Required {
            get {
                return ResourceManager.GetString("SocialReason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado del funcionario es obligatorio.
        /// </summary>
        public static string State_Required {
            get {
                return ResourceManager.GetString("State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de identificación.
        /// </summary>
        public static string TypeId_Required {
            get {
                return ResourceManager.GetString("TypeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campu usuario es obligatorio.
        /// </summary>
        public static string User_Required {
            get {
                return ResourceManager.GetString("User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo usuario es obligatorio y corresponde al correo electronico de registro.
        /// </summary>
        public static string UserMail_Required {
            get {
                return ResourceManager.GetString("UserMail_Required", resourceCulture);
            }
        }
    }
}
