//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeEmpleoVirutal.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenciaDeEmpleoVirutal.Entities.Resources.EntityMessages", typeof(EntityMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo dirección es obligatorio.
        /// </summary>
        public static string Address_Required {
            get {
                return ResourceManager.GetString("Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario agent es requerido.
        /// </summary>
        public static string AgentUser_Required {
            get {
                return ResourceManager.GetString("AgentUser_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario caller es requerido.
        /// </summary>
        public static string CallUser_Required {
            get {
                return ResourceManager.GetString("CallUser_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Requerida.
        /// </summary>
        public static string Category_Required {
            get {
                return ResourceManager.GetString("Category_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El telefono no es valido.
        /// </summary>
        public static string CellPhon_Number {
            get {
                return ResourceManager.GetString("CellPhon_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ingresar por lo menos un telefono de contacto.
        /// </summary>
        public static string Cellphones_Required {
            get {
                return ResourceManager.GetString("Cellphones_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo ciudad es obligatorio.
        /// </summary>
        public static string City_Required {
            get {
                return ResourceManager.GetString("City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo nombre de contacto es obligatorio.
        /// </summary>
        public static string ContactName_Required {
            get {
                return ResourceManager.GetString("ContactName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo departamento es obligatorio.
        /// </summary>
        public static string Dept_Required {
            get {
                return ResourceManager.GetString("Dept_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del dispositivo es requirido.
        /// </summary>
        public static string Device_Required {
            get {
                return ResourceManager.GetString("Device_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no es valido.
        /// </summary>
        public static string EmailAddress_FormatEmail {
            get {
                return ResourceManager.GetString("EmailAddress_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electronico es requerido.
        /// </summary>
        public static string EmailAddress_Required {
            get {
                return ResourceManager.GetString("EmailAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fin requerida.
        /// </summary>
        public static string EndDate_Required {
            get {
                return ResourceManager.GetString("EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo genero es obligatorio.
        /// </summary>
        public static string Genre_Required {
            get {
                return ResourceManager.GetString("Genre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo identificación es obligatorio.
        /// </summary>
        public static string Id_Required {
            get {
                return ResourceManager.GetString("Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Parametro Requerido.
        /// </summary>
        public static string IdParameter__Required {
            get {
                return ResourceManager.GetString("IdParameter__Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido es obligatorio.
        /// </summary>
        public static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El token de acceso al la llamada es obligatorio.
        /// </summary>
        public static string OpenTokAccessToken_Required {
            get {
                return ResourceManager.GetString("OpenTokAccessToken_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Session Id es requerido.
        /// </summary>
        public static string OpenTokSessionId_Required {
            get {
                return ResourceManager.GetString("OpenTokSessionId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener minimo 8 caracteres.
        /// </summary>
        public static string Password_LengthPassword {
            get {
                return ResourceManager.GetString("Password_LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo contraseña es obligatorio.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo excede la cantidad de caracteres permitida.
        /// </summary>
        public static string PDIField_Length {
            get {
                return ResourceManager.GetString("PDIField_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos del PDI son requeridos.
        /// </summary>
        public static string PDIField_Required {
            get {
                return ResourceManager.GetString("PDIField_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo del funcionario es obligatorio.
        /// </summary>
        public static string Position_Required {
            get {
                return ResourceManager.GetString("Position_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol del funcionario es requerido.
        /// </summary>
        public static string Role_Required {
            get {
                return ResourceManager.GetString("Role_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El puntaje de la llamada es requerido.
        /// </summary>
        public static string Score_Required {
            get {
                return ResourceManager.GetString("Score_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El session id es requerido.
        /// </summary>
        public static string SessionId_Required {
            get {
                return ResourceManager.GetString("SessionId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo razón social de la empresa es obligatorio.
        /// </summary>
        public static string SocialReason_Required {
            get {
                return ResourceManager.GetString("SocialReason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio requerida.
        /// </summary>
        public static string StartDate_Required {
            get {
                return ResourceManager.GetString("StartDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado del funcionario es obligatorio.
        /// </summary>
        public static string State_Required {
            get {
                return ResourceManager.GetString("State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la llamada es requerido.
        /// </summary>
        public static string StateCall_Required {
            get {
                return ResourceManager.GetString("StateCall_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la llamada no es valido.
        /// </summary>
        public static string StateCall_Valid {
            get {
                return ResourceManager.GetString("StateCall_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El token id es requerido.
        /// </summary>
        public static string TokenId_Required {
            get {
                return ResourceManager.GetString("TokenId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de identificación.
        /// </summary>
        public static string TypeId_Required {
            get {
                return ResourceManager.GetString("TypeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario es obligatorio y corresponde al noDoc_CodTypeDoc.
        /// </summary>
        public static string User_Required {
            get {
                return ResourceManager.GetString("User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe definir el tipo de usuario a registrar.
        /// </summary>
        public static string UserType_Required {
            get {
                return ResourceManager.GetString("UserType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor parametro rerquerido.
        /// </summary>
        public static string ValueParameter_Required {
            get {
                return ResourceManager.GetString("ValueParameter_Required", resourceCulture);
            }
        }
    }
}
