//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeEmpleoVirutal.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenciaDeEmpleoVirtual.Entities.Resources.EntityMessages", typeof(EntityMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo token de seguridad es obligatorio..
        /// </summary>
        public static string AuthenticateRequest_TokenMail_Required {
            get {
                return ResourceManager.GetString("AuthenticateRequest_TokenMail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Numero de Celular es obligatorio.
        /// </summary>
        public static string CreateAgentRequest_CellPhone_Required {
            get {
                return ResourceManager.GetString("CreateAgentRequest_CellPhone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Compañias es obligatorio.
        /// </summary>
        public static string CreateAgentRequest_Companies_Required {
            get {
                return ResourceManager.GetString("CreateAgentRequest_Companies_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Nombre es obligatorio.
        /// </summary>
        public static string CreateAgentRequest_FirstName_Required {
            get {
                return ResourceManager.GetString("CreateAgentRequest_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Apellidos es obligatorio.
        /// </summary>
        public static string CreateAgentRequest_LastName_Required {
            get {
                return ResourceManager.GetString("CreateAgentRequest_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de llamada no es valida..
        /// </summary>
        public static string DateCallRequest_DateCall_CurrentDate {
            get {
                return ResourceManager.GetString("DateCallRequest_DateCall_CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de correo electrónico es obligatoria..
        /// </summary>
        public static string DateCallRequest_EmailUserAddress_Required {
            get {
                return ResourceManager.GetString("DateCallRequest_EmailUserAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo token es obligatorio.
        /// </summary>
        public static string DateCallRequest_OpenTokAccessToken_Required {
            get {
                return ResourceManager.GetString("DateCallRequest_OpenTokAccessToken_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Session Id es obligatorio..
        /// </summary>
        public static string DateCallRequest_OpenTokSessionId_Required {
            get {
                return ResourceManager.GetString("DateCallRequest_OpenTokSessionId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la llamada es obligatorio..
        /// </summary>
        public static string DateCallRequest_State_Required {
            get {
                return ResourceManager.GetString("DateCallRequest_State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la llamada no es valido.
        /// </summary>
        public static string DateCallRequest_State_Valid {
            get {
                return ResourceManager.GetString("DateCallRequest_State_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción de la llamada es obligatoria..
        /// </summary>
        public static string DateCallRequest_Trace_Required {
            get {
                return ResourceManager.GetString("DateCallRequest_Trace_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de cliente es requerido (Web/Mobile).
        /// </summary>
        public static string GenerateTokenMailRequest_ClientType_Required {
            get {
                return ResourceManager.GetString("GenerateTokenMailRequest_ClientType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador de dispositivo es obligatorio..
        /// </summary>
        public static string GenerateTokenMailRequest_DeviceId_Required {
            get {
                return ResourceManager.GetString("GenerateTokenMailRequest_DeviceId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de correo electrónico no es valida..
        /// </summary>
        public static string GenerateTokenMailRequest_EmailAddress_FormatEmail {
            get {
                return ResourceManager.GetString("GenerateTokenMailRequest_EmailAddress_FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de correo electrónico es obligatoria..
        /// </summary>
        public static string GenerateTokenMailRequest_EmailAddress_Required {
            get {
                return ResourceManager.GetString("GenerateTokenMailRequest_EmailAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad uno es requerida..
        /// </summary>
        public static string Sample_PropertyOne_Required {
            get {
                return ResourceManager.GetString("Sample_PropertyOne_Required", resourceCulture);
            }
        }
    }
}
