//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeEmpleoVirutal.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametersApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametersApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenciaDeEmpleoVirutal.Utils.Resources.ParametersApp", typeof(ParametersApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;es&quot;&gt;&lt;head&gt;
        ///&lt;title&gt;Mail-Token&lt;/title&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///   &lt;table style=&quot;width:600px;&quot;&gt;
        ///       &lt;tbody&gt;
        ///           &lt;tr&gt;&lt;td&gt;&lt;img src=&quot;https://filesasesorenlineaig.blob.core.windows.net/images/mail-header.jpg&quot;&gt;&lt;/td&gt;&lt;/tr&gt;
        ///           &lt;tr&gt;
        ///               &lt;td style=&quot;text-align: center;&quot;&gt;
        ///                   &lt;p style=&quot; text-align: center; font-family: Helvetica; font-size: 24px; color:#605e5e&quot;&gt;Bienvenido&lt;/p&gt;
        ///                    &lt;span style=&quot; text-align: center; font-family:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMail {
            get {
                return ResourceManager.GetString("BodyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColsubsidioApp.
        /// </summary>
        public static string KeyCrypt {
            get {
                return ResourceManager.GetString("KeyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insight123resultxyz.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e84ad660c4721ae0e84ad660c4721ae0.
        /// </summary>
        public static string StringArray {
            get {
                return ResourceManager.GetString("StringArray", resourceCulture);
            }
        }
    }
}
