//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeEmpleoVirutal.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametersApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametersApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenciaDeEmpleoVirutal.Utils.Resources.ParametersApp", typeof(ParametersApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;text-align: center;&quot;&gt;
        ///&lt;p style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;Pass&lt;/p&gt;
        ///&lt;span style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;{0} {1}&lt;/span&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///&lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;Buen d&amp;iacute;a: Agradecemos por haberte registrado en la Agencia de Empleo Colsubsidio. Recuerda ingresar a www.agenciadeem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailPass {
            get {
                return ResourceManager.GetString("BodyMailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;text-align: center;&quot;&gt;
        ///&lt;p style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;Bienvenido&lt;/p&gt;
        ///&lt;span style=&quot;text-align: center; font-family: Helvetica; font-size: 24px; color: #605e5e;&quot;&gt;{0} {1}&lt;/span&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///&lt;p style=&quot;text-align: justify; font-family: Helvetica; font-size: 15px; color: #605e5e;&quot;&gt;Buen d&amp;iacute;a: Agradecemos por haberte registrado en la Agencia de Empleo Colsubsidio. Recuerda ingresar a www.agenc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailWelcome {
            get {
                return ResourceManager.GetString("BodyMailWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colsubsidioprueba@gmail.com.
        /// </summary>
        public static string EmailAddressFrom {
            get {
                return ResourceManager.GetString("EmailAddressFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColsubsidioApp.
        /// </summary>
        public static string KeyCrypt {
            get {
                return ResourceManager.GetString("KeyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia Virtual de empleo.
        /// </summary>
        public static string NameEmail {
            get {
                return ResourceManager.GetString("NameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insight123resultxyz.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e84ad660c4721ae0e84ad660c4721ae0.
        /// </summary>
        public static string StringArray {
            get {
                return ResourceManager.GetString("StringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar Contraseña Usuario Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectPass {
            get {
                return ResourceManager.GetString("SubJectPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Exitoso Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectWelcome {
            get {
                return ResourceManager.GetString("SubJectWelcome", resourceCulture);
            }
        }
    }
}
