//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeEmpleoVirutal.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametersApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametersApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenciaDeEmpleoVirutal.Utils.Resources.ParametersApp", typeof(ParametersApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;title&gt;Subsidy-Mail&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;table width=&apos;100%&apos; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;background-color: #F4F4F4;&apos;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;&lt;table  width=&apos;700&apos; max-width: 650px; min-width: 320px; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;margin: 0 auto; background-color:white;&apos; &gt;
        ///        &lt;tbody &gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&apos;{4}/assets/images/images/header.jpg&apos;&gt;&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///          &lt;tr&gt;
        ///&lt;td co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodiMailRequestSubsidy {
            get {
                return ResourceManager.GetString("BodiMailRequestSubsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;title&gt;Subsidy-Mail&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;table width=&apos;100%&apos; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;background-color: #F4F4F4;&apos;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;&lt;table  width=&apos;700&apos; max-width: 650px; min-width: 320px; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;margin: 0 auto; background-color:white;&apos; &gt;
        ///        &lt;tbody &gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&apos;{6}/assets/images/images/header.jpg&apos;&gt;&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailNotificationSubsidy {
            get {
                return ResourceManager.GetString("BodyMailNotificationSubsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td &gt;{0} {1}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td &gt;
        ///Por favor ingrese al siguiente link para completar el proceso de cambio de clave. &lt;br/&gt; {2}.
        ///&lt;/span&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        public static string BodyMailPass {
            get {
                return ResourceManager.GetString("BodyMailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;title&gt;Subsidy-Mail&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;table width=&apos;100%&apos; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;background-color: #F4F4F4;&apos;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;&lt;table  width=&apos;700&apos; max-width: 650px; min-width: 320px; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;margin: 0 auto; background-color:white;&apos; &gt;
        ///        &lt;tbody &gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&apos;{2}/assets/images/images/header.jpg&apos;&gt;&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///          &lt;tr&gt;
        ///&lt;td co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailPDI {
            get {
                return ResourceManager.GetString("BodyMailPDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;title&gt;Subsidy-Mail&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;table width=&apos;100%&apos; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;background-color: #F4F4F4;&apos;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;&lt;table  width=&apos;700&apos; max-width: 650px; min-width: 320px; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;margin: 0 auto; background-color:white;&apos; &gt;
        ///        &lt;tbody &gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&apos;{2}/assets/images/images/header.jpg&apos;&gt;&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///          &lt;tr&gt;
        ///&lt;td co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailUpate {
            get {
                return ResourceManager.GetString("BodyMailUpate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;title&gt;Untitled Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///&lt;table width=&apos;100%&apos; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;background-color: #F4F4F4;&apos;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;&lt;table  width=&apos;700&apos; max-width: 650px; min-width: 320px; border=&apos;0&apos; cellspacing=&apos;0&apos; cellpadding=&apos;0&apos; style=&apos;margin: 0 auto; background-color:white;&apos; &gt;
        ///        &lt;tbody &gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&apos;{1}/assets/images/images/header.jpg&apos;&gt;&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///           
        ///		   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailWelcomeCompany {
            get {
                return ResourceManager.GetString("BodyMailWelcomeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;utf-8&apos;&gt;
        ///&lt;meta http-equiv=Content-Type content=&apos;text/html; charset=windows-1252&apos;&gt;
        ///&lt;meta name=ProgId content=Word.Document&gt;
        ///&lt;meta name=Generator content=&apos;Microsoft Word 15&apos;&gt;
        ///&lt;meta name=Originator content=&apos;Microsoft Word 15&apos;&gt;
        ///&lt;link rel=File-List href=&apos;ini_files/filelist.xml&apos;&gt;
        ///&lt;link rel=themeData href=&apos;ini_files/themedata.thmx&apos;&gt;
        ///&lt;link rel=colorSchemeMapping href=&apos;ini_files/colorschememapping.xml&apos;&gt;
        ///
        ///&lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body lang=EN-US link=blue vlink=&apos;#954F72&apos; style= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyMailWelcomePerson {
            get {
                return ResourceManager.GetString("BodyMailWelcomePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&quot;0&quot; style=&quot;width: 900px&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=”Content-Type” content=”text/html; charset=UTF-8″ /&gt;
        ///&lt;/head&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr style=&quot;background:#00425f&quot;&gt;
        ///			&lt;td colspan=&quot;7&quot; style=&quot;text-align: center&quot;&gt;&lt;img src={11} alt=&quot;&quot;&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr style=&quot;background:#00597c; padding: 10px;&quot;&gt;
        ///			&lt;td colspan=&quot;7&quot; style=&quot;text-align: left&quot;&gt;&lt;img src={12} alt=&quot;&quot;&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td colspan=&quot;7&quot; style=&quot;padding: 10px; text-align: center; color:#00425f; font-size: 18px; font-family: sans-ser [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentPDIPdf {
            get {
                return ResourceManager.GetString("ContentPDIPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colsubsidioprueba@gmail.com.
        /// </summary>
        public static string EmailAddressFrom {
            get {
                return ResourceManager.GetString("EmailAddressFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColsubsidioApp.
        /// </summary>
        public static string KeyCrypt {
            get {
                return ResourceManager.GetString("KeyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia Virtual de empleo.
        /// </summary>
        public static string NameEmail {
            get {
                return ResourceManager.GetString("NameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insight123resultxyz.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e84ad660c4721ae0e84ad660c4721ae0.
        /// </summary>
        public static string StringArray {
            get {
                return ResourceManager.GetString("StringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar Contraseña Usuario Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectPass {
            get {
                return ResourceManager.GetString("SubJectPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento PDI Agencia Virtual de Empleo.
        /// </summary>
        public static string SubjectPDI {
            get {
                return ResourceManager.GetString("SubjectPDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidio Colsubsidio.
        /// </summary>
        public static string SubjectSubsidyRequest {
            get {
                return ResourceManager.GetString("SubjectSubsidyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización Exitosa Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectUpdate {
            get {
                return ResourceManager.GetString("SubJectUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Exitoso Agencia de Empleo Virtual Colsubsidio..
        /// </summary>
        public static string SubJectWelcome {
            get {
                return ResourceManager.GetString("SubJectWelcome", resourceCulture);
            }
        }
    }
}
